name: Issue Manager

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  issues:
    types: [opened, reopened]

jobs:
  close-stale-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check for stale issues
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been automatically closed due to inactivity. If you still need help, please feel free to reopen it.'
          stale-issue-label: 'stale'
          days-before-stale: 30
          days-before-close: 7
          exempt-issue-labels: 'pinned,help-wanted'
          only-issue-labels: ''
          operations-per-run: 30 